package server

const viewerTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=5">
<title>Wander</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
html{background:#0a0a0a}
body{background:#0a0a0a;color:#e5e7eb;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;line-height:1.75;margin:0;padding:0;min-height:100vh}
main{max-width:768px;margin:0 auto;padding:1rem}
article{background:#111827;border:1px solid #1f2937;border-radius:.75rem;padding:1.5rem}
h1,h2,h3,h4,h5,h6{color:#f3f4f6;margin-top:1.5em;margin-bottom:.5em}
p{margin:.75em 0}
a{color:#60a5fa}
a:hover{color:#93c5fd}
code{background:#1f2937;padding:.15em .4em;border-radius:.25em;font-size:.875em;-webkit-text-size-adjust:none;text-size-adjust:none}
pre{background:#1f2937;padding:1em;border-radius:.5em;overflow-x:auto;max-width:100%%;-webkit-overflow-scrolling:touch;margin:1em 0;-webkit-text-size-adjust:none;text-size-adjust:none}
pre span[style*="display:flex"]{display:block!important}
pre code{background:0 0;padding:0;-webkit-text-size-adjust:none;text-size-adjust:none}
ul,ol{margin:.75em 0;padding-left:1.5em}
li{margin:.25em 0}
blockquote{border-left:4px solid #374151;padding-left:1em;color:#9ca3af;font-style:italic;margin:1em 0}
table{width:100%%;border-collapse:collapse;margin:1em 0;overflow-x:auto;display:block}
th,td{border:1px solid #374151;padding:.5em .75em;text-align:left}
th{background:#1f2937;font-weight:600}
tr:nth-child(even){background:#111827}
dl{margin:.75em 0}
dt{color:#f3f4f6;font-weight:600;margin-top:.75em}
dd{margin-left:1.5em;margin-bottom:.5em;color:#d1d5dc}
hr{border-color:#374151;margin:1.5em 0}
input[type=checkbox]{margin-right:.5em;accent-color:#3b82f6}
img{max-width:100%%;height:auto;display:block}
.mermaid{background:#1f2937;border:1px solid #374151;border-radius:.5em;padding:1em;margin:1em 0;overflow-x:auto}
::-webkit-scrollbar{width:8px;height:8px}
::-webkit-scrollbar-track{background:#1f2937}
::-webkit-scrollbar-thumb{background:#4b5563;border-radius:4px}
</style>
</head>
<body>
<main>
<article>
%s
</article>
<p style="text-align:center;color:#4b5563;font-size:.875rem;margin-top:1.5rem">Generated by Wander</p>
</main>
<script>
mermaid.initialize({
  startOnLoad: false,
  theme: 'dark',
  themeVariables: {
    primaryColor: '#1f2937',
    primaryTextColor: '#f3f4f6',
    primaryBorderColor: '#4b5563',
    lineColor: '#9ca3af',
    secondaryColor: '#374151',
    tertiaryColor: '#111827',
    background: '#111827',
    mainBkg: '#1f2937',
    secondBkg: '#374151',
    nodeBorder: '#4b5563',
    clusterBkg: '#111827',
    clusterBorder: '#374151',
    titleColor: '#f3f4f6',
    edgeLabelBackground: '#1f2937',
    nodeTextColor: '#f3f4f6'
  },
  flowchart: {
    curve: 'basis',
    padding: 16
  }
});

document.addEventListener('DOMContentLoaded', function() {
  var blocks = document.querySelectorAll('pre code.language-mermaid');
  blocks.forEach(function(block) {
    var pre = block.parentElement;
    var text = block.textContent || block.innerText;
    var div = document.createElement('div');
    div.className = 'mermaid';
    div.textContent = text.trim();
    pre.parentNode.replaceChild(div, pre);
  });
  mermaid.init();
});
</script>
</body>
</html>`
