import { notFound } from "next/navigation";
import { getNote } from "@/lib/db";
import MarkdownRenderer from "@/components/MarkdownRenderer";

interface NotePageProps {
  params: Promise<{ id: string }>;
}

export default async function NotePage({ params }: NotePageProps) {
  const { id } = await params;
  const noteId = parseInt(id, 10);

  if (isNaN(noteId)) {
    notFound();
  }

  const note = getNote(noteId);

  if (!note) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-gray-950 py-8 px-4">
      <div className="max-w-3xl mx-auto">
        <article className="bg-gray-900 border border-gray-800 rounded-xl p-6 sm:p-8 min-w-0">
          <MarkdownRenderer content={note.content} />
        </article>
        <p className="text-center text-gray-600 text-sm mt-6">
          Generated by Wander
        </p>
      </div>
    </main>
  );
}
